import type { EnemyDef } from "../../../shared/auto-battler-types";

export const ENEMIES: EnemyDef[] = [
  {
    id: "null_pointer",
    name: "Null Pointer",
    emoji: "👻",
    description: "A phantom that phases through defenses.",
    tier: 1,
    stats: {
      hp: 35,
      attack: 8,
      attackSpeed: 2,
      range: 1,
      defense: 0,
      mana: 0,
      manaPerAttack: 0,
    },
    ability: null,
    targeting: "random",
    isBoss: false,
    soulValue: 1,
  },
  {
    id: "memory_leak",
    name: "Memory Leak",
    emoji: "🫠",
    description: "Grows stronger as it consumes resources.",
    tier: 2,
    stats: {
      hp: 55,
      attack: 6,
      attackSpeed: 3,
      range: 1,
      defense: 2,
      mana: 30,
      manaPerAttack: 10,
    },
    ability: {
      id: "leak_grow",
      name: "Leak & Grow",
      description: "Permanently gains +3 attack",
      manaCost: 30,
      effects: [{ type: "buff", stat: "attack", value: 3, duration: 999 }],
      targetType: "self",
    },
    targeting: "nearest",
    isBoss: false,
    soulValue: 2,
  },
  {
    id: "ddos_swarm",
    name: "DDoS Swarm",
    emoji: "🐝",
    description: "Individually weak, overwhelmingly numerous.",
    tier: 1,
    stats: {
      hp: 14,
      attack: 3,
      attackSpeed: 1,
      range: 1,
      defense: 0,
      mana: 0,
      manaPerAttack: 0,
    },
    ability: null,
    targeting: "random",
    isBoss: false,
    soulValue: 0,
  },
  {
    id: "race_condition",
    name: "Race Condition",
    emoji: "🏁",
    description: "Strikes fast and unpredictably.",
    tier: 2,
    stats: {
      hp: 40,
      attack: 12,
      attackSpeed: 1,
      range: 2,
      defense: 1,
      mana: 40,
      manaPerAttack: 14,
    },
    ability: {
      id: "collide",
      name: "Collide",
      description: "Damages a random enemy for 25",
      manaCost: 40,
      effects: [{ type: "damage", value: 25, scaling: 1 }],
      targetType: "nearest",
    },
    targeting: "random",
    isBoss: false,
    soulValue: 2,
  },
  {
    id: "sql_injection",
    name: "SQL Injection",
    emoji: "💉",
    description: "Pierces defenses. Targets databases.",
    tier: 2,
    stats: {
      hp: 50,
      attack: 10,
      attackSpeed: 2,
      range: 2,
      defense: 1,
      mana: 35,
      manaPerAttack: 12,
    },
    ability: {
      id: "drop_tables",
      name: "DROP TABLES",
      description: "Hits the highest attack unit for 35",
      manaCost: 35,
      effects: [{ type: "damage", value: 35, scaling: 1.5 }],
      targetType: "highest_attack",
    },
    targeting: "highest_attack",
    isBoss: false,
    soulValue: 3,
  },
  {
    id: "kernel_panic",
    name: "Kernel Panic",
    emoji: "💥",
    description: "Erratic but devastating when triggered.",
    tier: 3,
    stats: {
      hp: 70,
      attack: 14,
      attackSpeed: 3,
      range: 1,
      defense: 3,
      mana: 50,
      manaPerAttack: 15,
    },
    ability: {
      id: "panic",
      name: "Panic",
      description: "Stuns a random enemy for 2 ticks and damages for 20",
      manaCost: 50,
      effects: [
        { type: "damage", value: 20, scaling: 1.3 },
        { type: "stun", duration: 2, chance: 1 },
      ],
      targetType: "nearest",
    },
    targeting: "random",
    isBoss: false,
    soulValue: 3,
  },
  {
    id: "deadlock",
    name: "Deadlock",
    emoji: "🪢",
    description: "Locks units down. Slow but unrelenting.",
    tier: 3,
    stats: {
      hp: 100,
      attack: 8,
      attackSpeed: 3,
      range: 1,
      defense: 4,
      mana: 45,
      manaPerAttack: 15,
    },
    ability: {
      id: "lock",
      name: "Lock",
      description: "Stuns the lowest HP unit for 3",
      manaCost: 45,
      effects: [{ type: "stun", duration: 3, chance: 1 }],
      targetType: "lowest_hp",
    },
    targeting: "lowest_hp",
    isBoss: false,
    soulValue: 4,
  },
  {
    id: "cron_daemon",
    name: "Cron Daemon",
    emoji: "⏰",
    description: "Strikes on schedule. Every few ticks, AoE.",
    tier: 3,
    stats: {
      hp: 65,
      attack: 9,
      attackSpeed: 2,
      range: 2,
      defense: 2,
      mana: 50,
      manaPerAttack: 12,
    },
    ability: {
      id: "cron_fire",
      name: "Cron Fire",
      description: "Damages all enemies in a row for 22",
      manaCost: 50,
      effects: [{ type: "damage", value: 22, scaling: 1.3 }],
      targetType: "aoe_row",
    },
    targeting: "nearest",
    isBoss: false,
    soulValue: 3,
  },
  {
    id: "phishing_link",
    name: "Phishing Link",
    emoji: "🎣",
    description: "Drains mana and debuffs.",
    tier: 2,
    stats: {
      hp: 40,
      attack: 7,
      attackSpeed: 2,
      range: 3,
      defense: 1,
      mana: 30,
      manaPerAttack: 15,
    },
    ability: {
      id: "phish",
      name: "Phish",
      description: "Debuffs attack -4 for 5 ticks",
      manaCost: 30,
      effects: [{ type: "debuff", stat: "attack", value: 4, duration: 5 }],
      targetType: "highest_attack",
    },
    targeting: "backline_first",
    isBoss: false,
    soulValue: 2,
  },
  {
    id: "zombie_process",
    name: "Zombie Process",
    emoji: "🧟",
    description: "Refuses to die. Revives once per combat.",
    tier: 2,
    stats: {
      hp: 45,
      attack: 9,
      attackSpeed: 3,
      range: 1,
      defense: 2,
      mana: 60,
      manaPerAttack: 10,
    },
    ability: {
      id: "revive",
      name: "Revive",
      description: "Heals self for 30",
      manaCost: 60,
      effects: [{ type: "heal", value: 30, scaling: 1.3 }],
      targetType: "self",
    },
    targeting: "nearest",
    isBoss: false,
    soulValue: 3,
  },
  {
    id: "ransomware_boss",
    name: "Ransomware",
    emoji: "🔒",
    description: "Encrypts your units, disabling them one by one.",
    tier: 4,
    stats: {
      hp: 280,
      attack: 13,
      attackSpeed: 3,
      range: 2,
      defense: 5,
      mana: 60,
      manaPerAttack: 15,
    },
    ability: {
      id: "encrypt",
      name: "Encrypt",
      description: "Stuns the highest attack unit for 3 ticks",
      manaCost: 60,
      effects: [{ type: "stun", duration: 3, chance: 1.0 }],
      targetType: "highest_attack",
    },
    targeting: "highest_attack",
    isBoss: true,
    soulValue: 12,
  },
  {
    id: "stack_overflow_boss",
    name: "Stack Overflow",
    emoji: "📚",
    description: "Overwhelms with recursive attacks.",
    tier: 5,
    stats: {
      hp: 420,
      attack: 18,
      attackSpeed: 2,
      range: 3,
      defense: 7,
      mana: 80,
      manaPerAttack: 14,
    },
    ability: {
      id: "recurse",
      name: "Recurse",
      description: "Hits every unit for 25",
      manaCost: 80,
      effects: [{ type: "damage", value: 25, scaling: 2 }],
      targetType: "aoe_all",
    },
    targeting: "random",
    isBoss: true,
    soulValue: 20,
  },
];

export const ENEMY_MAP: Record<string, EnemyDef> = Object.fromEntries(
  ENEMIES.map((e) => [e.id, e]),
);
