import type { ProgressionNode } from "../../../shared/auto-battler-types";

export const PROGRESSION_NODES: ProgressionNode[] = [
  {
    id: "extra_gold",
    name: "Seed Funding",
    description: "+3 starting gold",
    emoji: "💵",
    category: "stat_boost",
    cost: 5,
    prerequisites: [],
    position: { x: 0, y: 0 },
    effect: { type: "starting_bonus", bonusType: "gold", value: 3 },
  },
  {
    id: "bigger_bench",
    name: "Bigger Bench",
    description: "+1 bench slot",
    emoji: "🪑",
    category: "mechanic",
    cost: 10,
    prerequisites: [],
    position: { x: 1, y: 0 },
    effect: { type: "starting_bonus", bonusType: "bench_size", value: 1 },
  },
  {
    id: "unlock_postgres",
    name: "Unlock PostgreSQL",
    description: "Adds PostgreSQL to the unit pool",
    emoji: "🐘",
    category: "unit_pool",
    cost: 15,
    prerequisites: ["extra_gold"],
    position: { x: 0, y: 1 },
    effect: { type: "unlock_unit", unitDefId: "postgresql" },
  },
  {
    id: "unlock_monitoring",
    name: "Monitoring Synergy",
    description: "Unlocks the Monitoring trait synergy",
    emoji: "📊",
    category: "synergy",
    cost: 20,
    prerequisites: ["bigger_bench"],
    position: { x: 1, y: 1 },
    effect: { type: "unlock_synergy", synergyId: "monitoring" },
  },
  {
    id: "unlock_prometheus",
    name: "Unlock Prometheus",
    description: "Adds Prometheus to the unit pool",
    emoji: "🔥",
    category: "unit_pool",
    cost: 15,
    prerequisites: ["unlock_monitoring"],
    position: { x: 1, y: 2 },
    effect: { type: "unlock_unit", unitDefId: "prometheus" },
  },
  {
    id: "unlock_jenkins",
    name: "Unlock Jenkins",
    description: "Adds Jenkins to the unit pool",
    emoji: "👴",
    category: "unit_pool",
    cost: 25,
    prerequisites: ["unlock_postgres"],
    position: { x: 0, y: 2 },
    effect: { type: "unlock_unit", unitDefId: "jenkins" },
  },
  {
    id: "hedge_fund_unlock",
    name: "Unlock Hedge Fund",
    description: "Relic pool gains Hedge Fund (+2 interest cap)",
    emoji: "🏦",
    category: "relic_pool",
    cost: 20,
    prerequisites: ["extra_gold"],
    position: { x: 2, y: 1 },
    effect: { type: "unlock_relic", relicDefId: "hedge_fund" },
  },
  {
    id: "unlock_stackoverflow",
    name: "Unlock SO Bookmark",
    description: "Adds Stack Overflow Bookmark relic",
    emoji: "🔖",
    category: "relic_pool",
    cost: 10,
    prerequisites: [],
    position: { x: 2, y: 0 },
    effect: { type: "unlock_relic", relicDefId: "stackoverflow_bookmark" },
  },
  {
    id: "unlock_bigger_monitor",
    name: "Unlock Bigger Monitor",
    description: "Adds Bigger Monitor relic (+1 shop slot)",
    emoji: "🖥️",
    category: "relic_pool",
    cost: 20,
    prerequisites: ["unlock_stackoverflow"],
    position: { x: 2, y: 2 },
    effect: { type: "unlock_relic", relicDefId: "bigger_monitor" },
  },
  {
    id: "unlock_pair_programmer",
    name: "Unlock Pair Programmer",
    description: "Adds Pair Programmer relic",
    emoji: "👥",
    category: "relic_pool",
    cost: 25,
    prerequisites: ["hedge_fund_unlock"],
    position: { x: 2, y: 3 },
    effect: { type: "unlock_relic", relicDefId: "pair_programmer" },
  },
  {
    id: "starting_hp",
    name: "Hardened Stack",
    description: "+10 starting server HP",
    emoji: "❤️",
    category: "stat_boost",
    cost: 15,
    prerequisites: ["bigger_bench"],
    position: { x: 3, y: 1 },
    effect: { type: "starting_bonus", bonusType: "hp", value: 10 },
  },
  {
    id: "starting_shop",
    name: "Bigger Shop",
    description: "+1 shop slot at run start",
    emoji: "🏪",
    category: "mechanic",
    cost: 30,
    prerequisites: ["starting_hp"],
    position: { x: 3, y: 2 },
    effect: { type: "starting_bonus", bonusType: "shop_size", value: 1 },
  },
  {
    id: "unlock_frontend_syn",
    name: "Frontend Synergy",
    description: "Unlocks the Frontend synergy",
    emoji: "🎨",
    category: "synergy",
    cost: 20,
    prerequisites: [],
    position: { x: 4, y: 0 },
    effect: { type: "unlock_synergy", synergyId: "frontend" },
  },
  {
    id: "unlock_orchestrator_syn",
    name: "Orchestrator Synergy",
    description: "Unlocks the Orchestrator synergy",
    emoji: "🎯",
    category: "synergy",
    cost: 25,
    prerequisites: ["unlock_frontend_syn"],
    position: { x: 4, y: 1 },
    effect: { type: "unlock_synergy", synergyId: "orchestrator" },
  },
  {
    id: "unlock_copilot",
    name: "Unlock GitHub Copilot",
    description: "Legendary relic that damages all enemies at combat start",
    emoji: "🤖",
    category: "relic_pool",
    cost: 50,
    prerequisites: ["unlock_orchestrator_syn", "unlock_pair_programmer"],
    position: { x: 4, y: 2 },
    effect: { type: "unlock_relic", relicDefId: "github_copilot" },
  },
  // --- Passive economy upgrades (mid/late game progression) ---
  {
    id: "caffeine_boost",
    name: "Caffeine Boost",
    description: "+2 gold income every round",
    emoji: "☕",
    category: "stat_boost",
    cost: 20,
    prerequisites: ["extra_gold"],
    position: { x: 5, y: 0 },
    effect: { type: "starting_bonus", bonusType: "income", value: 2 },
  },
  {
    id: "hot_reload",
    name: "Hot Reload",
    description: "+1 free reroll at the start of every round",
    emoji: "♻️",
    category: "mechanic",
    cost: 25,
    prerequisites: ["caffeine_boost"],
    position: { x: 5, y: 1 },
    effect: { type: "starting_bonus", bonusType: "free_reroll", value: 1 },
  },
  {
    id: "cheap_laptop",
    name: "Cheap Laptop",
    description: "Reroll cost reduced by 1 gold",
    emoji: "💻",
    category: "mechanic",
    cost: 20,
    prerequisites: ["hot_reload"],
    position: { x: 5, y: 2 },
    effect: { type: "starting_bonus", bonusType: "reroll_cost", value: 1 },
  },
  {
    id: "hype_train",
    name: "Hype Train",
    description: "+1 gold on win/loss streak bonus",
    emoji: "🚄",
    category: "stat_boost",
    cost: 25,
    prerequisites: ["extra_gold"],
    position: { x: 1, y: 3 },
    effect: { type: "starting_bonus", bonusType: "streak_bonus", value: 1 },
  },
  {
    id: "devs_crying",
    name: "Devs Crying",
    description: "+2 gold when you lose a combat",
    emoji: "😭",
    category: "stat_boost",
    cost: 20,
    prerequisites: [],
    position: { x: 0, y: 3 },
    effect: { type: "starting_bonus", bonusType: "loss_gold", value: 2 },
  },
  {
    id: "second_screen",
    name: "Second Screen",
    description: "+1 bench slot (stacks with Bigger Bench)",
    emoji: "🖥️",
    category: "mechanic",
    cost: 30,
    prerequisites: ["bigger_bench"],
    position: { x: 2, y: 3 },
    effect: { type: "starting_bonus", bonusType: "bench_size", value: 1 },
  },
  {
    id: "diversified_portfolio",
    name: "Diversified Portfolio",
    description: "+2 max interest per round",
    emoji: "📈",
    category: "stat_boost",
    cost: 35,
    prerequisites: ["hedge_fund_unlock"],
    position: { x: 3, y: 3 },
    effect: { type: "starting_bonus", bonusType: "interest_cap", value: 2 },
  },
];

export const PROGRESSION_MAP: Record<string, ProgressionNode> =
  Object.fromEntries(PROGRESSION_NODES.map((n) => [n.id, n]));

// Default unlocked synergies (available before any progression purchase)
export const DEFAULT_UNLOCKED_SYNERGIES: string[] = [
  "infrastructure",
  "database",
  "cache",
];
