import type { UnitDef } from "../../../shared/auto-battler-types";

// 13 unit defs for MVP
export const UNITS: UnitDef[] = [
  {
    id: "nginx",
    name: "Nginx",
    emoji: "🛡️",
    description: "A sturdy reverse proxy. Soaks damage for the team.",
    tier: 1,
    role: "tank",
    traits: ["infrastructure", "proxy"],
    baseStats: {
      hp: 90,
      attack: 6,
      attackSpeed: 3,
      range: 1,
      defense: 4,
      mana: 50,
      manaPerAttack: 10,
    },
    starScaling: { hpMult: 1.8, attackMult: 1.3, abilityMult: 1.5 },
    ability: {
      id: "load_balance",
      name: "Load Balance",
      description: "Shields self for 30 HP",
      manaCost: 50,
      effects: [{ type: "shield", value: 30, duration: 3 }],
      targetType: "self",
    },
    targeting: "nearest",
  },
  {
    id: "redis",
    name: "Redis",
    emoji: "⚡",
    description: "Blazing fast in-memory attacker. Fragile but deadly.",
    tier: 2,
    role: "dps",
    traits: ["database", "cache"],
    baseStats: {
      hp: 45,
      attack: 14,
      attackSpeed: 1,
      range: 2,
      defense: 1,
      mana: 40,
      manaPerAttack: 15,
    },
    starScaling: { hpMult: 1.5, attackMult: 1.8, abilityMult: 1.8 },
    ability: {
      id: "cache_burst",
      name: "Cache Burst",
      description: "Blasts an enemy row for 25 damage",
      manaCost: 40,
      effects: [{ type: "damage", value: 25, scaling: 1.5 }],
      targetType: "aoe_row",
    },
    targeting: "highest_attack",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    emoji: "🐘",
    description: "Reliable heavy-hitting database. Tanky and powerful.",
    tier: 3,
    role: "tank",
    traits: ["database", "infrastructure"],
    baseStats: {
      hp: 120,
      attack: 10,
      attackSpeed: 3,
      range: 1,
      defense: 5,
      mana: 60,
      manaPerAttack: 12,
    },
    starScaling: { hpMult: 1.7, attackMult: 1.4, abilityMult: 1.6 },
    ability: {
      id: "vacuum",
      name: "Vacuum",
      description: "Hits nearest enemy for 35 and heals self for 20",
      manaCost: 60,
      effects: [
        { type: "damage", value: 35, scaling: 1.5 },
        { type: "heal", value: 20, scaling: 1.3 },
      ],
      targetType: "nearest",
    },
    targeting: "nearest",
  },
  {
    id: "nodejs",
    name: "Node.js",
    emoji: "🟢",
    description: "Versatile backend runtime. Balanced attacker.",
    tier: 2,
    role: "dps",
    traits: ["backend", "runtime"],
    baseStats: {
      hp: 55,
      attack: 11,
      attackSpeed: 2,
      range: 2,
      defense: 2,
      mana: 45,
      manaPerAttack: 12,
    },
    starScaling: { hpMult: 1.6, attackMult: 1.6, abilityMult: 1.6 },
    ability: {
      id: "event_loop",
      name: "Event Loop",
      description: "Rapid damage to the highest-attack enemy",
      manaCost: 45,
      effects: [{ type: "damage", value: 30, scaling: 1.6 }],
      targetType: "highest_attack",
    },
    targeting: "lowest_hp",
  },
  {
    id: "docker",
    name: "Docker",
    emoji: "🐳",
    description: "Containerizes damage. Buffs allies.",
    tier: 3,
    role: "support",
    traits: ["infrastructure", "orchestrator"],
    baseStats: {
      hp: 70,
      attack: 7,
      attackSpeed: 3,
      range: 2,
      defense: 3,
      mana: 70,
      manaPerAttack: 10,
    },
    starScaling: { hpMult: 1.6, attackMult: 1.4, abilityMult: 1.9 },
    ability: {
      id: "containerize",
      name: "Containerize",
      description: "Buffs ally attack +6 for 5 ticks",
      manaCost: 70,
      effects: [{ type: "buff", stat: "attack", value: 6, duration: 5 }],
      targetType: "ally_lowest_hp",
    },
    targeting: "nearest",
  },
  {
    id: "react",
    name: "React",
    emoji: "⚛️",
    description: "Reactive frontend damage dealer. Fast reflexes.",
    tier: 2,
    role: "assassin",
    traits: ["frontend"],
    baseStats: {
      hp: 40,
      attack: 13,
      attackSpeed: 1,
      range: 2,
      defense: 1,
      mana: 40,
      manaPerAttack: 14,
    },
    starScaling: { hpMult: 1.5, attackMult: 1.7, abilityMult: 1.8 },
    ability: {
      id: "rerender",
      name: "Re-render",
      description: "Stuns the lowest HP enemy for 2 ticks",
      manaCost: 40,
      effects: [{ type: "stun", duration: 2, chance: 1.0 }],
      targetType: "lowest_hp",
    },
    targeting: "backline_first",
  },
  {
    id: "express",
    name: "Express",
    emoji: "🚂",
    description: "Lean middleware framework. Quick responses.",
    tier: 1,
    role: "dps",
    traits: ["backend", "runtime"],
    baseStats: {
      hp: 50,
      attack: 9,
      attackSpeed: 2,
      range: 2,
      defense: 1,
      mana: 35,
      manaPerAttack: 14,
    },
    starScaling: { hpMult: 1.5, attackMult: 1.6, abilityMult: 1.5 },
    ability: {
      id: "middleware",
      name: "Middleware Chain",
      description: "Damages nearest for 20",
      manaCost: 35,
      effects: [{ type: "damage", value: 20, scaling: 1.5 }],
      targetType: "nearest",
    },
    targeting: "nearest",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    emoji: "🍃",
    description: "Flexible document store. Heals allies.",
    tier: 2,
    role: "support",
    traits: ["database"],
    baseStats: {
      hp: 60,
      attack: 6,
      attackSpeed: 3,
      range: 2,
      defense: 2,
      mana: 55,
      manaPerAttack: 12,
    },
    starScaling: { hpMult: 1.6, attackMult: 1.3, abilityMult: 1.8 },
    ability: {
      id: "aggregate",
      name: "Aggregate",
      description: "Heals lowest HP ally for 35",
      manaCost: 55,
      effects: [{ type: "heal", value: 35, scaling: 1.6 }],
      targetType: "ally_lowest_hp",
    },
    targeting: "nearest",
  },
  {
    id: "prometheus",
    name: "Prometheus",
    emoji: "🔥",
    description: "Metrics collector. Marks enemies for extra damage.",
    tier: 3,
    role: "support",
    traits: ["monitoring"],
    baseStats: {
      hp: 55,
      attack: 8,
      attackSpeed: 2,
      range: 3,
      defense: 2,
      mana: 50,
      manaPerAttack: 13,
    },
    starScaling: { hpMult: 1.5, attackMult: 1.4, abilityMult: 1.8 },
    ability: {
      id: "alert_fire",
      name: "Alert Fire",
      description: "Debuffs target defense -3 for 6 ticks",
      manaCost: 50,
      effects: [{ type: "debuff", stat: "defense", value: 3, duration: 6 }],
      targetType: "highest_attack",
    },
    targeting: "highest_attack",
  },
  {
    id: "grafana",
    name: "Grafana",
    emoji: "📊",
    description: "Dashboard visionary. Reveals enemies for bonus DPS.",
    tier: 2,
    role: "support",
    traits: ["monitoring", "frontend"],
    baseStats: {
      hp: 50,
      attack: 7,
      attackSpeed: 2,
      range: 3,
      defense: 2,
      mana: 50,
      manaPerAttack: 11,
    },
    starScaling: { hpMult: 1.5, attackMult: 1.4, abilityMult: 1.7 },
    ability: {
      id: "dashboard",
      name: "Dashboard",
      description: "Buffs all allies attack +4 for 4 ticks",
      manaCost: 50,
      effects: [{ type: "buff", stat: "attack", value: 4, duration: 4 }],
      targetType: "aoe_all",
    },
    targeting: "nearest",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    emoji: "👴",
    description: "Aging CI butler. Slow but unstoppable.",
    tier: 4,
    role: "tank",
    traits: ["infrastructure", "orchestrator"],
    baseStats: {
      hp: 160,
      attack: 12,
      attackSpeed: 4,
      range: 1,
      defense: 6,
      mana: 80,
      manaPerAttack: 10,
    },
    starScaling: { hpMult: 1.8, attackMult: 1.5, abilityMult: 2.0 },
    ability: {
      id: "build_pipeline",
      name: "Build Pipeline",
      description: "Damages all enemies for 30 and stuns for 1",
      manaCost: 80,
      effects: [
        { type: "damage", value: 30, scaling: 1.8 },
        { type: "stun", duration: 1, chance: 0.6 },
      ],
      targetType: "aoe_all",
    },
    targeting: "nearest",
  },
  {
    id: "kafka",
    name: "Kafka",
    emoji: "📨",
    description: "Streaming messages. Relentless partitioned attacks.",
    tier: 4,
    role: "dps",
    traits: ["backend", "orchestrator"],
    baseStats: {
      hp: 75,
      attack: 16,
      attackSpeed: 2,
      range: 3,
      defense: 2,
      mana: 70,
      manaPerAttack: 12,
    },
    starScaling: { hpMult: 1.7, attackMult: 1.7, abilityMult: 2.0 },
    ability: {
      id: "publish_storm",
      name: "Publish Storm",
      description: "DoT to backline enemies — 15/tick for 4 ticks",
      manaCost: 70,
      effects: [{ type: "dot", damagePerTick: 15, duration: 4 }],
      targetType: "aoe_row",
    },
    targeting: "backline_first",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    emoji: "☸️",
    description: "Orchestrates allies. Rare and game-changing.",
    tier: 5,
    role: "support",
    traits: ["infrastructure", "orchestrator"],
    baseStats: {
      hp: 90,
      attack: 10,
      attackSpeed: 3,
      range: 2,
      defense: 4,
      mana: 100,
      manaPerAttack: 10,
    },
    starScaling: { hpMult: 1.8, attackMult: 1.5, abilityMult: 2.2 },
    ability: {
      id: "auto_scale",
      name: "Auto-Scale",
      description: "Heals all allies for 40 and buffs attack +5",
      manaCost: 100,
      effects: [
        { type: "heal", value: 40, scaling: 2.0 },
        { type: "buff", stat: "attack", value: 5, duration: 6 },
      ],
      targetType: "aoe_all",
    },
    targeting: "nearest",
  },
  // ─── New units ───
  {
    id: "github_actions",
    name: "GitHub Actions",
    emoji: "🎬",
    description: "CI/CD automation. Hits hard on a schedule.",
    tier: 3,
    role: "dps",
    traits: ["ci", "infrastructure"],
    baseStats: {
      hp: 60,
      attack: 14,
      attackSpeed: 2,
      range: 2,
      defense: 2,
      mana: 50,
      manaPerAttack: 14,
    },
    starScaling: { hpMult: 1.6, attackMult: 1.7, abilityMult: 1.8 },
    ability: {
      id: "workflow_dispatch",
      name: "Workflow Dispatch",
      description: "Hits all enemies for 20 damage",
      manaCost: 50,
      effects: [{ type: "damage", value: 20, scaling: 1.6 }],
      targetType: "aoe_all",
    },
    targeting: "lowest_hp",
  },
  {
    id: "terraform",
    name: "Terraform",
    emoji: "🏗️",
    description: "Infrastructure as code. Builds defenses from scratch.",
    tier: 3,
    role: "support",
    traits: ["infrastructure", "ci"],
    baseStats: {
      hp: 75,
      attack: 6,
      attackSpeed: 3,
      range: 2,
      defense: 4,
      mana: 60,
      manaPerAttack: 11,
    },
    starScaling: { hpMult: 1.7, attackMult: 1.3, abilityMult: 1.9 },
    ability: {
      id: "apply_plan",
      name: "Apply Plan",
      description: "Shields all allies for 20 HP",
      manaCost: 60,
      effects: [{ type: "shield", value: 20, duration: 4 }],
      targetType: "aoe_all",
    },
    targeting: "nearest",
  },
  {
    id: "redis_cluster",
    name: "Redis Cluster",
    emoji: "⚡",
    description: "Distributed caching powerhouse. Buffs team speed.",
    tier: 4,
    role: "support",
    traits: ["database", "cache"],
    baseStats: {
      hp: 80,
      attack: 9,
      attackSpeed: 2,
      range: 2,
      defense: 3,
      mana: 65,
      manaPerAttack: 12,
    },
    starScaling: { hpMult: 1.7, attackMult: 1.5, abilityMult: 2.0 },
    ability: {
      id: "cluster_sync",
      name: "Cluster Sync",
      description: "All allies attack 1 tick faster for 5 ticks",
      manaCost: 65,
      effects: [{ type: "buff", stat: "attackSpeed", value: -1, duration: 5 }],
      targetType: "aoe_all",
    },
    targeting: "nearest",
  },
  {
    id: "elk_stack",
    name: "ELK Stack",
    emoji: "🦌",
    description: "Elasticsearch, Logstash, Kibana. Sees everything.",
    tier: 4,
    role: "dps",
    traits: ["monitoring", "observability"],
    baseStats: {
      hp: 70,
      attack: 18,
      attackSpeed: 2,
      range: 3,
      defense: 2,
      mana: 60,
      manaPerAttack: 13,
    },
    starScaling: { hpMult: 1.6, attackMult: 1.8, abilityMult: 2.0 },
    ability: {
      id: "log_analysis",
      name: "Log Analysis",
      description: "Debuffs all enemies defense -4 for 5 ticks",
      manaCost: 60,
      effects: [{ type: "debuff", stat: "defense", value: 4, duration: 5 }],
      targetType: "aoe_all",
    },
    targeting: "highest_attack",
  },
  {
    id: "jest",
    name: "Jest",
    emoji: "🃏",
    description: "Testing framework. Exposes enemy weaknesses.",
    tier: 1,
    role: "dps",
    traits: ["testing", "frontend"],
    baseStats: {
      hp: 40,
      attack: 10,
      attackSpeed: 2,
      range: 2,
      defense: 1,
      mana: 35,
      manaPerAttack: 14,
    },
    starScaling: { hpMult: 1.5, attackMult: 1.6, abilityMult: 1.6 },
    ability: {
      id: "assertion",
      name: "Assertion",
      description: "Debuffs target defense -3 for 4 ticks",
      manaCost: 35,
      effects: [{ type: "debuff", stat: "defense", value: 3, duration: 4 }],
      targetType: "lowest_hp",
    },
    targeting: "lowest_hp",
  },
  {
    id: "vault",
    name: "Vault",
    emoji: "🔐",
    description: "Secrets management. Protects the squad.",
    tier: 3,
    role: "tank",
    traits: ["security", "infrastructure"],
    baseStats: {
      hp: 110,
      attack: 7,
      attackSpeed: 3,
      range: 1,
      defense: 6,
      mana: 65,
      manaPerAttack: 10,
    },
    starScaling: { hpMult: 1.8, attackMult: 1.3, abilityMult: 1.8 },
    ability: {
      id: "seal_secrets",
      name: "Seal Secrets",
      description: "Shields self for 40 and buffs defense +3",
      manaCost: 65,
      effects: [
        { type: "shield", value: 40, duration: 4 },
        { type: "buff", stat: "defense", value: 3, duration: 6 },
      ],
      targetType: "self",
    },
    targeting: "nearest",
  },
  {
    id: "datadog",
    name: "Datadog",
    emoji: "🐕",
    description: "Full-stack observability. Sees and bites.",
    tier: 5,
    role: "dps",
    traits: ["monitoring", "observability"],
    baseStats: {
      hp: 85,
      attack: 20,
      attackSpeed: 2,
      range: 3,
      defense: 3,
      mana: 80,
      manaPerAttack: 12,
    },
    starScaling: { hpMult: 1.7, attackMult: 1.9, abilityMult: 2.2 },
    ability: {
      id: "full_trace",
      name: "Full Trace",
      description:
        "Deals 50 damage to highest-attack enemy and debuffs attack -5",
      manaCost: 80,
      effects: [
        { type: "damage", value: 50, scaling: 2.0 },
        { type: "debuff", stat: "attack", value: 5, duration: 5 },
      ],
      targetType: "highest_attack",
    },
    targeting: "highest_attack",
  },
  {
    id: "cypress",
    name: "Cypress",
    emoji: "🌲",
    description: "E2E testing assassin. Hunts the backline.",
    tier: 2,
    role: "assassin",
    traits: ["testing", "frontend"],
    baseStats: {
      hp: 42,
      attack: 15,
      attackSpeed: 1,
      range: 2,
      defense: 1,
      mana: 40,
      manaPerAttack: 15,
    },
    starScaling: { hpMult: 1.5, attackMult: 1.8, abilityMult: 1.8 },
    ability: {
      id: "e2e_strike",
      name: "E2E Strike",
      description: "Massive 40 damage to backline target",
      manaCost: 40,
      effects: [{ type: "damage", value: 40, scaling: 1.8 }],
      targetType: "lowest_hp",
    },
    targeting: "backline_first",
  },
];

export const UNIT_MAP: Record<string, UnitDef> = Object.fromEntries(
  UNITS.map((u) => [u.id, u]),
);

// Default starting pool (not locked behind progression)
export const DEFAULT_UNLOCKED_UNITS: string[] = [
  "nginx",
  "redis",
  "nodejs",
  "docker",
  "react",
  "express",
  "mongodb",
  "grafana",
  "kafka",
  "kubernetes",
  "jest",
  "cypress",
  "github_actions",
  "terraform",
  "vault",
];
