import type { MilestoneDef } from "../../../shared/repo-tycoon-types";

export const MILESTONES: MilestoneDef[] = [
  {
    id: "first-commit",
    requires: { resource: "commits", amount: 1 },
    title: "First Commit",
    description: "Initial commit. Message was 'wip'.",
    impact: "small",
    flags: ["show-commit-graph"],
  },
  {
    id: "first-pr",
    requires: { resource: "prs", amount: 1 },
    title: "First PR Merged",
    description: "LGTM. Ship it.",
    impact: "small",
    flags: ["show-activity-feed"],
    rewards: [{ type: "grant_resource", resource: "contributors", amount: 1 }],
  },
  {
    id: "on-a-roll",
    requires: { resource: "commits", amount: 10 },
    title: "On a Roll",
    description: "Ten commits down. The muscle memory is forming.",
    impact: "small",
    flags: [],
    rewards: [{ type: "grant_resource", resource: "contributors", amount: 1 }],
  },
  {
    id: "early-adopters",
    requires: { resource: "stars", amount: 100 },
    title: "Early Adopters",
    description: "Your first 100 stars. Someone actually used this.",
    impact: "small",
    flags: [],
    rewards: [
      { type: "grant_resource", resource: "contributors", amount: 2 },
      { type: "event_chance_mult", mult: 1.1 },
    ],
  },
  {
    id: "regular-contributor",
    requires: { resource: "prs", amount: 10 },
    title: "Regular Contributions",
    description: "Ten PRs merged. This is becoming a real project.",
    impact: "small",
    flags: [],
    rewards: [{ type: "grant_resource", resource: "contributors", amount: 3 }],
  },
  {
    id: "gaining-traction",
    requires: { resource: "stars", amount: 500 },
    title: "Gaining Traction",
    description: "500 stars. People are recommending you to their colleagues.",
    impact: "small",
    flags: [],
    rewards: [
      { type: "grant_resource", resource: "contributors", amount: 3 },
      { type: "tick_rate_mult", resource: "loc", mult: 1.2 },
    ],
  },
  {
    id: "commit-streak",
    requires: { resource: "commits", amount: 100 },
    title: "Commit Streak",
    description: "100 commits. GitHub is showing you a long green streak.",
    impact: "medium",
    flags: [],
    rewards: [{ type: "tick_rate_mult", resource: "loc", mult: 1.3 }],
  },
  {
    id: "trending",
    requires: { resource: "stars", amount: 1_000 },
    title: "Trending on GitHub",
    description: "The algorithm blessed you.",
    impact: "medium",
    flags: ["show-trending-banner"],
    rewards: [
      { type: "grant_resource", resource: "contributors", amount: 5 },
      { type: "event_chance_mult", mult: 1.2 },
    ],
  },
  {
    id: "consistent-maintainer",
    requires: { resource: "prs", amount: 50 },
    title: "Consistent Maintainer",
    description: "50 PRs. Your commit graph is an unbroken wall of green.",
    impact: "medium",
    flags: [],
    rewards: [
      { type: "conversion_ratio_mult", from: "prs", to: "stars", mult: 1.5 },
      { type: "grant_resource", resource: "contributors", amount: 5 },
    ],
  },
  {
    id: "developer-darling",
    requires: { resource: "stars", amount: 5_000 },
    title: "Developer Darling",
    description: "5 000 stars. Framework authors are citing you.",
    impact: "medium",
    flags: [],
    rewards: [
      { type: "tick_rate_mult", resource: "loc", mult: 1.5 },
      { type: "grant_resource", resource: "contributors", amount: 8 },
    ],
  },
  {
    id: "hn-frontpage",
    requires: { resource: "stars", amount: 10_000 },
    title: "Front Page of HN",
    description: "\"I was not expecting the traffic.\"",
    impact: "large",
    flags: ["show-contributor-swarm", "show-hn-banner"],
    rewards: [
      { type: "grant_resource", resource: "contributors", amount: 15 },
      { type: "event_chance_mult", mult: 1.5 },
    ],
  },
  {
    id: "hall-of-fame",
    requires: { resource: "stars", amount: 50_000 },
    title: "Hall of Fame",
    description: "50 000 stars. Listed on Awesome Lists in seven languages.",
    impact: "large",
    flags: [],
    rewards: [
      { type: "conversion_ratio_mult", from: "prs", to: "stars", mult: 2 },
      { type: "grant_resource", resource: "contributors", amount: 20 },
    ],
  },
  {
    id: "corporate-sponsors",
    requires: { resource: "stars", amount: 100_000 },
    title: "Corporate Sponsors",
    description: "Logos in the README now.",
    impact: "huge",
    flags: ["theme-gold", "show-sponsor-tiles"],
    rewards: [
      { type: "grant_resource", resource: "sponsors", amount: 3 },
      { type: "tick_rate_mult", resource: "loc", mult: 2 },
    ],
  },
  {
    id: "unicorn",
    requires: { resource: "stars", amount: 1_000_000 },
    title: "Open Source Unicorn",
    description: "Someone offers to acquire you. You say maybe.",
    impact: "huge",
    flags: ["theme-gold", "show-confetti", "show-unicorn"],
    rewards: [
      { type: "grant_resource", resource: "sponsors", amount: 10 },
      { type: "tick_rate_mult", resource: "loc", mult: 3 },
      { type: "conversion_ratio_mult", from: "prs", to: "stars", mult: 3 },
    ],
  },
];

export const MILESTONE_MAP: Record<string, MilestoneDef> = Object.fromEntries(
  MILESTONES.map((m) => [m.id, m]),
);
